name: 公民團體與人權工作者資安陪伴計畫
name_en: Digital Security Support for CSOs and HRDs in Taiwan
 

description: 透過一年期長期陪伴，協助 6 個高風險組織檢視數位工具、帳號、資料與工作流程，建立可落實的資安政策或守則。計畫產出 3 份成果報告與 1 份網站教材，並在陪伴過程中成功攔截一起針對公民社會的資安攻擊事件。
description_en: The Open Culture Foundation’s Security Makeover Program for CSOs and HRDs accompanied six Taiwan-based organizations for one year to review tools, accounts, data, and workflows, and to develop practical security policies or guidelines. The program produced three public reports and one learning resource, and helped stop a cyberattack targeting civil society before it caused harm.


tagline: 
tagline_en: 

og_image: /p/defendhrd/defendhrd logo_tw.png
og_image_en: /p/defendhrd/defendhrd logo_en.png
header_image: 
avatar_image: 
theme_color: 

start: 
end: 

topic_ids:
  - infosec
field_ids:
  - it
tags:
tags_en:

links:
  - title: 【報告】台灣人權與民主倡議團體數位威脅概況
    url: https://drive.google.com/file/d/1sxAFmSiJL6DzdO3ezq_hJSBROuGXNLAA/view?usp=drive_link
    color: 
    icon: file outline
  - title: 【報告】守護倡議之聲：公民團體與人權工作者資安陪伴計畫成果報告
    url: https://drive.google.com/file/d/1wgYdObezFzlI6OJLozzqQF5Vt11B7gCd/view?usp=drive_link
    color: 
    icon: file outline
  - title: 【報告】信任的代價：一場針對臺灣人權工作者的資安攻擊與防守實錄
    url: https://drive.google.com/file/d/1VwZwVXpOjTBZibVCTbIF1wUdPhQU_wJz/view?usp=drive_link
    color: 
    icon: file outline
  - title: 【教材】資安新手村 (SSD)
    url: https://ssd.ocf.tw/
    color: 
    icon: world icon
links_en:
  - title: "[Report] Digital Security Mapping for HRDs in Taiwan"
    url: https://drive.google.com/file/d/1VV12Rp7IKkWexNTKQRuWIA4Zfd8ztN9X/view?usp=drive_link
    color: 
    icon: file outline
  - title: "[Report] Safeguarding Advocacy"
    url: https://drive.google.com/file/d/1ln6__KiGZgf9QSkYhwKo8gm4L9d9tExo/view?usp=drive_link
    color: 
    icon: file outline
  - title: "[Report] The Cost of Trust"
    url: https://drive.google.com/file/d/1Q3Z2nLJ4dkQpmSqXQcctl4IW3cUhdDkF/view?usp=drive_link
    color: 
    icon: file outline
  - title: "[Learning Resource] Shield of Self-Defense (SSD)"
    url: https://ssd.ocf.tw/
    color: 
    icon: world icon

organizer_ids:
  - ocf
co-organizer_ids:
consultant_ids:

board_ids:

staff_ids:
  - Singing
  - weichen
  - rosa
  - SzuHui
  - CSTang
  - Toomore
  - Jin

listed: yes
listed_en: yes
