name: Twinkle AI
name_en: 

description: Twinkle AI 是一個以繁體中文為核心的開源 AI 社群，專注於打造在地語言模型與資料集。我們致力於推動可公開使用的模型權重、訓練資料與實務經驗分享，串聯研究者、工程師與創作者，促進台灣在地 AI 生態的交流與共創。
description_en: 

abbr: 
abbr_en: 

tagline: 
tagline_en: 

og_image: /p/twinkleai/twinkleai-logo.png
header_image: 
avatar_image: 
theme_color: 

start: 
end: 

type_ids:
  - community
topic_ids:
  - misc
field_ids:
  - ai
tags:
tags_en:

metas:
metas_en:

links:
  - title: 捐款網頁
    url: https://neti.cc/x58Ym4q

links_en:

actions:

actions_en:

advisor_ids:
organizer_ids:
  - twinkleai
co-organizer_ids:
implementer_ids:
sponsor_ids:

coordinator_ids:

case-handler_ids:
co-worker_ids:
consultant_ids:
volunteer_ids:
contributor_ids:
donors:
donors_en:

board_ids:
staff_ids:


listed: yes
listed_en:

reports:
